# R Script
# Author: leerssej
# Date: 19 Nov 2016
# Desc: Street sweeper functions to standardize domestic and international street addresses
# Desc: Standardization to align with dominant googleMaps address information formats
# Desc: Extensive Secondary unit designator removal to improve validity of googleMaps ddress verification/geocoding
# Desc: Country specific (conditional) address cleansing functions to apply only on a subset of particular countries 
        # feed the function (address, countryName) such that the country names comply with those listed in the function
# Desc: Language specific (conditional) address cleansing functions to apply on subset of addresses classified according to designated languages
        # feed the function (address, LanguageCode) such that the language codes comply with the ISO 639-1 codes listed in the function
        ## See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for further details

StSwpR <- function(x) {
x <- gsub("([a-z])'S", "\\1's", x, ignore.case = T)
x <- gsub("^-$", NA, x) 
x <- gsub(" - ", " ", x) 
x <- gsub("    ", " ", x) 
x <- gsub("([\\D])-([\\S])", "\\1 \\2 ", x) 
x <- gsub("_", " ", x) 
x <- gsub("\\`", " ", x) 
x <- gsub("\\'(\\s+|$)", " ", x) 
x <- gsub("(^|\\s+)\\'(?!s)", " ", x, ignore.case = T, perl = T) 
x <- gsub("\\?", " ", x, ignore.case = T)
x <- gsub("@", " ", x, ignore.case = T)
# fix the general issues
x <- gsub("\\.", " ", x, ignore.case = T)
x <- gsub(",", " ", x, ignore.case = T)
x <- gsub(":", " ", x, ignore.case = T)
x <- gsub(";", " ", x, ignore.case = T)
x <- gsub("^C/\\s+", "Calle ", x, ignore.case = T)
x <- gsub("/", " ", x, ignore.case = T)
x <- gsub("\\\"", " ", x, ignore.case = T)
x <- gsub("^&", " ", x, ignore.case = T)
x <- gsub("\\s*&\\s*", " and ", x, ignore.case = T)
x <- gsub("\\*", " ", x, ignore.case = T)
x <- gsub("\\#", " ", x, ignore.case = T)
x <- gsub("\\(", " ", x, ignore.case = T)
x <- gsub("\\)", " ", x, ignore.case = T)
x <- gsub("\\s*\\!\\s*", " ", x, ignore.case = T)
x <- gsub("(')*s Gravendijkwal", "'s-Gravendijkwal", x, ignore.case = T)
x <- gsub(" Of ", " of ", x, ignore.case = T)
x <- gsub(" The ", " the ", x, ignore.case = T)
x <- gsub(" D([a,e,i,o,u]) ", " d\\1 ", x, ignore.case = T)
x <- gsub(" Des ", " des ", x, ignore.case = T)
x <- gsub(" Et ", " et ", x, ignore.case = T)
x <- gsub(" Y ", " y ", x, ignore.case = T)
x <- gsub(" L Hopital", " l'Hopital", x, ignore.case = T)
x <- gsub(" L([a,e,o]) ", " l\\1 ", x, ignore.case = T)
# I am aware that most of below are not actually post boxes, but I want all the attendant data
# stripped in similar fashion as with boites postales so it is simple and expedient to later transform all similars by same rule. 
x <- gsub("(^|\\s+)P(ost)*\\s*O(ffice)*\\s*B(ox)*(\\s+|\\d+)", " Bp ", x, ignore.case = T)
x <- gsub("(^|\\s+)C(ampus)*\\s*B(ox)*(\\s+|-)", " Bp ", x, ignore.case = T)
x <- gsub("(^|\\s+)P(rivate)*\\s*B(ag)*(\\s+|-)", " Bp ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Du|M)*M(ail)*\\s*C(ode)*(\\s+|-)(?!.*(Dermot|Parkstad|Cullough))", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Ms(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Mailbox(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Local(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Workstation(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)lucpq(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)crc(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Hwcrc(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Dock(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Haus(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Gebae*ude(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Geb(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Postboks(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Indgang(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Oficina(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Escalera(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Sotano(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Afsnit(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Quai(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Tsa(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Mailpoint(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Management(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Zona(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Sektor(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Postbus(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Consultorio(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)T A V \\w+\\s*\\w*(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Post(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Post(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)B P(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Conj(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)lucpq(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Simard(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Cuerpo(\\s+|$)", " Bp ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Bp\\s*X*o*\\s*\\w?\\s*-*\\d+(-\\d)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Bp\\s\\w?\\d+-\\w{1,3}(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Bp\\s+.*$", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(Dumc\\s+)*(Post\\s*)*Box\\s*(No\\s+)*(\\w?|\\w?-*\\d+\\w?)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cedex\\s*[0-9]*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)P A(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("  ", " ", x, ignore.case = T)
x <- gsub("((^|\\s+)(\\d+\\s*i*e*(r|me)*\\sEt\\s+)*[0-9]+\\s*i*e*(r|me)*\\sEta*g*e*(\\s+|$))|((^|\\s+)Eta*ge*\\s*[0-9]+\\s*i*e*(r|me)*(\\s+|$))", " ", x, perl = T, ignore.case = T)
x <- gsub("((^|\\s+)Po*rte*\\s+\\w*\\s*[0-9]+\\s*i*e*(r|me)*(\\s+|$))", " ", x, ignore.case = T)
x <- gsub("((^|\\s+)(Bocage|Gate)\\s+\\w*\\s*[0-9]+\\s*i*e*(r|me)*(\\s+|$))", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Entrance\\s+(\\w?|\\s*[0-9]+\\s*i*e*(r|me)*(Off\\s+))(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Entrance\\s+\\w*\\s*[0-9]+\\s*i*e*(r|me)*c*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Unite\\s+\\D*,", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Unite\\s+(\\S+(\\s+|$))*", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)First|Primer(a|o)*\\s+", " 1st ", x, ignore.case = T)
x <- gsub("(^|\\s+)(One|Uno)\\s+", " 1 ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Second|Segund(a|o)*)\\s+", " 2nd ", x, ignore.case = T)
x <- gsub("(^|\\s+)Two(\\s+|$)", " 2 ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Third|Tercer(a|o)*)\\s+", " 3rd ", x, ignore.case = T)
x <- gsub("(^|\\s+)Three(\\s+|$)", " 3 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Fourth\\s+", " 4th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Four(\\s+|$)", " 4 ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Fifth|Quinto\\s+)", " 5th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Five(\\s+|$)", " 5 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Sixth\\s+", " 6th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Six(\\s+|$)", " 6 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Seventh\\s+", " 7th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Seven(\\s+|$)", " 7 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Eighth\\s+", " 8th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Eight(\\s+|$)", " 8 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ninth\\s+", " 9th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Nine(\\s+|$)", " 9 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Tenth\\s+", " 10th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ten(\\s+|$)", " 10 ", x, ignore.case = T)
x <- gsub("(^|\\s+)Eleventh\\s+", " 11th ", x, ignore.case = T)
x <- gsub("(^|\\s+)Eleven(\\s+|$)", " 11th ", x, ignore.case = T)
# Floor Clean and Purge
x <- gsub("(^|\\s+)Andar(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)Piso(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)Planta(\\s(Baja|Semisotano|Sotano|Ss|semisoterrani))*(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Anneau Central\\s+)*Rez\\s+(De\\s+)*Chaussee*(\\s+(Bas|Haut))*(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Ni|Le)ve(l|au)(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)Lvl(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Sub)*-*basement(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)Subsolo(\\s+|$)", " Floor ", x, ignore.case = T)
x <- gsub("(^|\\s+)Rue\\s+Ste(?!\\s+Catherine)(\\s+|$)", " Rue Sainte ", x, perl = T, ignore.case = T)
x <- gsub("(^|\\s+)Stes*(?!\\s+(Catherine|Mar\\w+|Elizabeth|Anne))(\\s+|$)", " Suite ", x, perl = T, ignore.case = T)
x <- gsub("(^|\\s+)Blo(que|cket)(\\s+|$)", " Block ", x, ignore.case = T)
x <- gsub("(^|\\s+)Bloco(\\s+|$)", " Block ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(Upper|Lower)*\\s*(Gr*ound|Mezzanine)\\s*Flo*o*r*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(\\d+|I|V|\\w)(a|b|c|er|st|nd|rd|th|o|to|do)\\s*Flo*o*r*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Flo*o*r*\\s*(No\\s+|-)*(\\d+\\w?|\\w)(?!.*\\s+(Rd|St|Dr)).*$", " ", x, ignore.case = T, perl = T)
x <- gsub("^\\s*Flo*o*r*\\s*(No\\s+|-)*\\d+", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+|-)(\\d+|I|V|\\w)(a|b|c|er|st|nd|rd|th|o|to|do)*\\s*Flo*o*r*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Mezzanine\\s*(No\\s+|-)*\\d+(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Mezzanine\\s*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Rm\\s*(\\s+|$)", " Room ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Sala\\s*(\\s+|$)", " Room ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Aile\\d*(\\s+|$)", " Wing ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Bureau(\\s+|$)", " Office ", x, ignore.case = T)
# Hospital and Clinic Rectifications
x <- gsub("(^|\\s+)Hos\\s*Pital(\\s+|$)", " Hospital ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cl*i\\s*n\\s*I\\s*q'*ues(\\s+|$)", " Cliniques ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cl*i\\s*n\\s*I\\s*ques(\\s+|$)", " Cliniques ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cli\\s*n\\s*I\\s*que(\\s+|$)", " Clinique ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cli\\s*n\\s*I\\s*(cal)*(\\s+|$)", " Clinical ", x, ignore.case = T)
x <- gsub("(^|\\s+)Tr\\s*i\\s*a\\s*ls*(\\s+|$)", " Trials ", x, ignore.case = T)
x <- gsub("(^|\\s+)On\\s*c\\s*O\\s*logy(\\s+|$)", " Oncology ", x, ignore.case = T)
x <- gsub("(^|\\s+)On\\s*Cologie(\\s+|$)", " Oncologie ", x, ignore.case = T)
x <- gsub("(^|\\s+)On\\s*Cologica(\\s+|$)", " Oncologica ", x, ignore.case = T)
x <- gsub("(^|\\s+)OnCo\\s*logica(\\s+|$)", " Oncologica ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Med\\s*)*OnCo(\\s+|$)", " Oncologica ", x, ignore.case = T)
x <- gsub("(^|\\s+)Oncologica(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ca\\s*n\\s*Cer(\\s+|$)", " Cancer ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ha*emot\\s*ologie(\\s+|$)", " Hematologie ", x, ignore.case = T)
# Department Research and Services
x <- gsub("(^|\\s+)Re\\s*s\\s*e\\s*arch(\\s+|$)", " Research ", x, ignore.case = T)
x <- gsub("(^|\\s+)Res(\\s+|$)", " Research ", x, ignore.case = T)
x <- gsub("(^|\\s+)Clin Res(\\s+|$)", " Clinical Research ", x, ignore.case = T)
x <- gsub("(^|\\s+)Clin Trials(\\s+|$)", " Clinical Trials ", x, ignore.case = T)
x <- gsub("(^|\\s+)Can Res(\\s+|$)", " Cancer Research ", x, ignore.case = T)
x <- gsub("(^|\\s+)Can Ctr(\\s+|$)", " Cancer Center ", x, ignore.case = T)
x <- gsub("(^|\\s+)Can(\\s+|$)", " Cancer ", x, ignore.case = T)
x <- gsub("(^|\\s+)Rsch(\\s+|$)", " Research ", x, ignore.case = T)
x <- gsub("(^|\\s+)De\\pt(\\s+|$)", " Department ", x, ignore.case = T)
x <- gsub("(^|\\s+)Depar\\s*tment(\\s+|$)", " Department ", x, ignore.case = T)
x <- gsub("(^|\\s+)Serv\\s*ices(\\s+|$)", " Services ", x, ignore.case = T)
x <- gsub("(^|\\s+)Rad\\s*ioterapie(\\s+|$)", " Services ", x, ignore.case = T)
x <- gsub("(^|\\s+)Chem\\s*other\\s*apy(\\s+|$)", " Services ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ess\\s*(ai\\s*(s|e)*)*\\s+Cliniques*(\\s+|$)", " Essais Cliniques ", x, ignore.case = T)
x <- gsub("(^|\\s+)Apo\\s*T\\s*h\\s*eke(\\s+|$)", " Apotheke ", x, ignore.case = T)
x <- gsub("ap\\s*o\\s*T\\s*heke(\\s+|$)", "apotheke ", x, ignore.case = T)
x <- gsub("(^|\\s+)Zentral\\s*a\\s*poth(eke)*(\\s+|$)", " Zentralapotheke ", x, ignore.case = T)
x <- gsub("apo\\s*Theek(\\s+|$)", "apotheek ", x, ignore.case = T)
x <- gsub("apo\\s*Teket(\\s+|$)", "apoteket ", x, ignore.case = T)
x <- gsub("Kli\\s*Nische(\\s+|$)", " Klinische ", x, ignore.case = T)
x <- gsub("(^|\\s+)Stu Dies(\\s+|$)", " Studies ", x, ignore.case = T)
# Center
x <- gsub("(^|\\s+)Ctr(\\s+|$)", " Center ", x, ignore.case = T)
# Building
x <- gsub("(^|\\s+)Build ing(\\s+|$)", " Building ", x, ignore.case = T)
x <- gsub("(^|\\s+)Buidling(\\s+|$)", " Building ", x, ignore.case = T)
x <- gsub("(^|\\s+)Bu*i*ldg*(\\s+|$)", " Building ", x, ignore.case = T)
x <- gsub("(^|\\s+)Mab(\\s+|$)", " Medical Arts Building ", x, ignore.case = T)
# Block purges
x <- gsub("(^|\\s+|-)(Main|North|South|East|West|Outpatient|Emergency|Centre|On-Call|Professorial|Clinical( Trial)*( Support)*( Services*)*|Lab(oratory)*|Tower|\\d*\\w{1,2})(?!.*\\s+(Rd|St|Dr))(\\s+|-)Blo*c*k\\s*.*$", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)(Blue|Green|Yellow|Teaching)(\\s+|-)Blo*c*k(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Blo*c*k(\\s+|-)(\\w|\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)\\d?-*\\w?\\s+Block(\\s+|$)", " ", x, ignore.case = T)
# Wing purges
x <- gsub("(^|\\s+)(Main|North|South|East|West|Outpatient|Emergency|Centre|On-Call|Professorial|Clinical( Trial)*( Support)*( Services*)*|Lab(oratory)*|Tower|Kent Ridge|\\d*\\w{1,2})\\s+Wing(\\s+\\d)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(\\w|\\d+)(\\s+|-)Wing(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)\\d?-*\\w?\\s+Wing(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(59th Medical|Atkinson Morley|-*Barr(i|e)nger|Bermondsey|Bexley|Burr|Cambridge|Cheyne|Claremont|Clarence|Crf Leazes|Daly|Daly|Fullham|Hambled(e|o)n|Healy|Healy|Horder|Horton|Jenner|Kenning|Knightsbridge|Lambeth|Leazes|Mint|New Victoria|New|Peter Howson|Southwar(d|k)|Sutton|Thornton|Wallace|Weller|Woolverstone|Elizabeth Garrett Anderson|chancellors)\\s+Wing(\\d|\\s+|-)*\\w?\\d*(\\s+|$)", " ", x, ignore.case = T)
# Pharmacy and Department fixes
x <- gsub("(^|\\s+)(Services\\s+)*Ph\\s*a\\s*r\\s*m\\s*A\\s*c\\s*y(\\s*Manufacturing)*(\\s+|$)", " Pharmacy ", x, ignore.case = T)
x <- gsub("(^|\\s+)Pharm Services(\\s+|$)", " Pharmacy Services", x, ignore.case = T)
x <- gsub("(^|\\s+)Ph\\s*a\\s*r\\s*m\\s*A\\s*cie(\\s*Centr*ale)*(\\s+|$)", " Pharmacie ", x, ignore.case = T)
x <- gsub("(^|\\s+)Fa\\s*r\\s*m\\s*A\\s*cia(\\s+|$)", " Farmacia ", x, ignore.case = T)
x <- gsub("(^|\\s+)Fa\\s*r\\s*m\\s*A\\s*ceuticos(\\s+|$)", " Farmacia ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Ph|F)a\\s*r\\s*m\\s*a*(c|s)*(i|ia|ie|y|euti(sk|cos)|ists*)(\\s+|$)", " Farmacia ", x, ignore.case = T)
x <- gsub("(^|\\s+)Far\\s*mAci(\\s+|$)", " Farmacia ", x, ignore.case = T)
x <- gsub("(^|\\s+)De*p\\s*art(a|e)*\\s*ment*o*(\\s+|$)", " Department ", x, ignore.case = T)
x <- gsub("(^|\\s+)Dep\\s*a*r*t(a|e)*\\s*m*e*n*t*o*(\\s+|$)", " Department ", x, ignore.case = T)
x <- gsub("(^|\\s+)De*pto*(\\s+|$)", " Department ", x, ignore.case = T)
# services purge
x <- gsub("(^|\\s+)Ser\\s*Vicos(\\s+|$)", " Servicos ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ser\\s*Vices*(?!\\s+Rd)(\\s+|$)", " Services ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+|-)(Dept of\\s+)*(Pharmac(y|eutical)|Farmacia) Services(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)In*vestigational(\\s+Chemo)*(\\s+Drug)*(\\s+Special)*\\s+Services*(\\s+Unit)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Medical|Acute|Clinical|Technical|Support)\\s+Services(\\s+Building)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Cardiothoracic Services(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Family|Clalit)\\s+Health Services(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(Clinical\\s*(Trials\\s*)*)*(Aseptic\\s*)*(Can\\s*cer\\s*)*(Re\\s*s(earch)*\\s*)*Services(?!\\s+Rd)(\\s+|$)", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Servici(o|e)\\s+\\w+olog(i(a|e)|y)(\\s+Pediatric(a)*)*(\\s+\\w+olog(i(a|e)|y))*(\\s+|$)", " ", x, ignore.case = T)
# Pharmacy expurgations
x <- gsub("(^|\\s+)((Ph|F)armac(ia|ie|y)*\\s+Department|Department\\s+(of\\s)*(\\w|\\d+-*\\d*|\\d+(\\s+(y|and|et)\\s+\\d+)*))(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("Servi(c|z)i*(o|e)s*\\s*(de\\s+)*(Ph|F)armac(ia|ie|y)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Ph|F)armac(ia|ie|y)\\s+(Internal*|Ospedaliera|Studi Clinici|Oncologica)(\\s*E)*(\\s*Sperimentali)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(Ph|F)armac(ia|ie|y)(?=\\s+\\d+)(\\s+|$)", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)(Zentral)*Apoth*ee*k(i|e)*t*( Klinis(che|k))*(\\s*experimenteel)*(De(r|s)(\\s+\\D+)*)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Apoth*ee*k(i|e)*t* Servici*os* )*(de )*(Clinical |Klinis(che|k) )*(Trials* )*(Main )*((In|Out)patient )*(Basement )*(\\w+olog(i(a|e)|y) )*(Investigational\\s+)*(Ph|F)arma*(c|s)*(i|ia|ie|y|euti(sk|cos)|ists*)*(\\s*Stores*)*( Clinical)*( Trials*)*((\\s+|-)Research)*( Office)*( Department)*(\\s+Rech\\s+erche)*(\\s+Clinique)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Ess(ais)* (Cliniques\\s*)*)*(Re*se*a*r*ch\\s*)*(Investigational )*(Ph|F)arma*c*(ia|ie|y)*(-Ids)*(-Research\\s*)*(Centr*a*le*\\s*)*(\\s*Services*)*(\\s*Unit)*( Osp(ediale)*)*(\\s+|$)", " ", x, ignore.case = T)
# Department
x <- gsub("(^|\\s+)Department\\s+(Rheum)*(of\\s*)*(Allergy\\s*)*(Asthma\\s*)*(and\\s*)*(Onco*l*o*g*((i(a|e))|y)*)*(Clinical*\\s*)*(Cardiac\\s*)*(Internal*\\s*)*(Immun\\s*)*(Research|Medicine|(Si\\s*)*\\w+olo*g(y|ie|ia)(\\s*and)*(\\s*Clinical)*(\\s*\\w+olo*g(y|ie|ia))*)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Department\\s+(Investigational\\s*)*((of|De)\\s*)*((Ph|F)armac*(ia|ie|y|eutical)*|\\w+olo*g(y|ie|ia)(\\s*and)*(\\s*Clinical)*(\\s*\\w+olo*g(y|ie|ia))*)(\\s*Services)*(\\s*Chirurgie)*(\\s*Digestive)*(\\s+Rech\\s+erche)*(\\s+Clinique)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Div(ision)*\\s+(Rheum)*(of )*(Allergy )*(Asthma )*(and )*(Onco*l*o*g*((i(a|e))|y)*)*(Clinical\\s*)*(Cardiac\\s*)*(Internal*\\s*)*(Immun\\s*)*(Research|Medicine|(Si\\s*)*\\w+olo*g(y|ie|ia)(\\s*and)*(\\s*Clinical)*(\\s*\\w+olo*g(y|ie|ia))*)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Outpatients\\s*)*(Investigational\\s*)*((Ph|F)arm*\\s*a*c*(ia|ie|y|eutical)*|\\w+olo*g(y|ie|ia)(\\s*and)*(\\s*Clinical)*(\\s*\\w+olo*g(y|ie|ia))*)(\\s*Manufacturing)*(\\s*Services)*(\\s*Chirurgie)*(\\s*Digestive)*\\s*Department(\\s*Clinical)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Department\\s+((of|De)\\s*)*Medecine(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)((\\w+o*l*o*g*(ia|ie|y)|Outpatients)*\\s+De*pa*r*te*m*e*n*t*o*)|(De*pa*r*te*m*e*n*t*o*\\s+(of\\s*)(Internal*\\s*)*(Med\\s*i*c*i*n*e*\\s*)*(Breast\\s*)*(Unit\\s*)*(Rheum)*)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)De*pa*r*te*m*e*n*t\\s+(of\\s*)*(Internal*\\s*)*(Med\\s*i*c*i*n*e*\\s*)*(Breast\\s*)*(Unit\\s*)*(Rheum)*(South)*(\\s+|$)", " ", x, ignore.case = T)
# Unit
x <- gsub("(^|\\s+)(Internal*\\s*)*(Med\\s*i*c*i*n*e*\\s*)*(Breast\\s*)*(Oncology\\s*)*(Day\\s*)*(Clin(ical)*\\s*)*(Trials\\s*)*(Res(earch)* \\s*)*(Business\\s*)*\\s*Unite*s*i*\\s*(Rheum)*(South)*(-*\\d+|\\s+(\\D\\d*|\\d+\\w|||w{1,2}))(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Internal*\\s*)*(Med\\s*i*c*i*n*e*\\s*)*(Breast\\s*)*(Oncology\\s*)*(Day\\s*)*(Clinical\\s*)*(Trials\\s*)*(Research\\s*)*(Business\\s*)*\\s*Unite*s*i*\\s*(Rheum\\s*)*(South\\s*)*(Kat\\s*)*(-*\\d+|\\s+(\\D\\d*|\\d+\\w|||w{1,2}))*(\\s+|$)", " ", x, ignore.case = T)
# Room
x <- gsub("(^|\\s+)Private\\s+Rooms*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Room\\s*-*\\d+-*\\d*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(Hsc\\s+)*Room\\s*(\\d*-*\\d*\\w\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Room\\s*(\\w{1,2}(-|\\s+)*\\d+(-|\\s+)*|\\w{1,2}\\d-\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Room\\s*(\\w|Ell|Hsc)\\d*(-|\\s+|n)*\\d+(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Room\\s+\\d*(-|\\s+)*\\w?\\d+\\w?(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Room\\s+\\w?(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Room\\s+\\d+\\w?-\\d*-*\\w?(\\s+|$)", " ", x, ignore.case = T)
# Pavillion
x <- gsub("(^|\\s+|-)(Faculty )*(Cancer )*(Res(earch)* )*(W*E*a*s*t* )*(Fell\\s+)*Pavillion\\s*(-*\\d|\\s+(\\w\\d*)|Leroyer)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)(Fell\\s+)*Pavil*li*on\\s*(Leroyer)*(\\w?)*(\\s+|$)", " ", x, ignore.case = T)
# Attn
x <- gsub("(^|\\s+)Attn-*(Investigational\\s+Drug\\s+)*(\\D+([0-9])|\\D+)(\\s+|$)", " ", x, ignore.case = T)
# Section
x <- gsub("(^|\\s+|-)Sec(t|c)(ion|(eu|o)r|ia)\\s*(-*\\d+|\\s+(\\D\\d*|\\d+\\w|))(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Sec(t|c)(ion|(eu|o)r|ia)\\s*(des\\s+)*Ess*ais Cliniques*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+|-)Sec(t|c)(ion|(eu|o)r|ia)\\s*Bleu(\\s+|$)", " ", x, ignore.case = T)
# Wing purges
x <- gsub("(^|\\s+)Wing(\\s+|-)(\\w|\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)\\d*\\w{1,2})\\s+Wing(\\s*\\d)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(\\w|\\d+)(\\s+|-)Wing(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Wing(\\s+|-)(\\w|\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)\\d?-*\\w?\\s+Wing(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Wing(\\s+Sud)*(\\s+et)*(\\s+O*u*est)*(\\s+|$)", " ", x, ignore.case = T)
#Ward & Batiment & Edificio
x <- gsub("(^|\\s+)C*\\s*O*\\s*(Main\\s+)*Ward(\\s+|-)(\\w|\\d+\\w?)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)(Waller|Charles Blackley|Old Faith|Main|Oncologi(v|c)al|Rheumatology)\\s+Ward(\\s+Block)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Edificio(\\s+|-)(\\w|\\w\\d+|\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Batiment(\\s+|-)(\\w|\\d+)(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Batiment(?!.*Blvd).*$", " ", x, ignore.case = T, perl = T)
# Suite Purges
x <- gsub("(^|\\s+)Suite(\\s+|-|\\d+)(\\w|\\w{1,2}-*\\d+|\\d+|\\d+\\w)-*\\d*\\w?(\\s+|$)", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+)Suite\\s$", " ", x, ignore.case = T)
# Loading Dock/Bay
x <- gsub("(^|\\s+)C*\\s*O*(Via)*\\s*-*Loading\\s+(Dock\\s*)*\\d*(Via)*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)C*\\s*O*(Via)*\\s*-*Loading\\s+(Dock\\s*)*(Bay\\s*)*\\d(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)C*\\s*O*(Via)*\\s*-*Loading\\s+(Dock\\s*)*(Bay\\s*)*(\\s+|$)", " ", x, ignore.case = T)
# Hyphen removal
x <- gsub("(^|\\s+)-(?=\\S+)", "", x, perl = T, ignore.case = T)
x <- gsub("([\\w])- ", "\\1", x, perl = T, ignore.case = T)
x <- gsub("(^|\\s+)C -(\\w?\\d+)*(\\s+|$)", " ", x, ignore.case = T)
# Single Word and Number Removal
x <- gsub("(^|\\s+)Centrale\\s$", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Clinique et Maternite$", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)Ensayos\\s+$", " ", x, ignore.case = T)
x <- gsub("^\\s+(des\\s+)*Essais\\s+Cliniques(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("^\\s+Ids(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("^\\s\\d\\s*$)", " ", x, ignore.case = T)
x <- gsub("^\\s*Plate-*forme Logistique\\s*\\w?\\d*(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("^\\s*\\d*\\w{1,2}(\\s|-)*\\w?\\d+$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\d+-*\\s*\\d*$)", " ", x, ignore.case = T)
x <- gsub("^\\s*de(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("^\\s*(and\\s+)*\\d+\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\w{1,2}\\s*$", " ", x, ignore.case = T)
x <- gsub("(^|\\s)(\\w?\\d+\\w?)*(the\\s+)*(Clinical\\s*|Research\\s*|Internal*\\s*|Med\\s*i*c*i*n*e*\\s*|Breast\\s*|Oncology\\s*|Day\\s*|Clinical\\s*(Trials\\s*|Research\\s*)*|Business\\s*|\\s*Unite*s*i*\\s*|Rheum|South|Medical\\s*|(Clinical\\s*)*Site Management\\s*|Aseptic\\s*|Can\\s*cer\\s*(Care(\\s*(Centre|Program))*|Re\\s*s(earch)*\\s*(Services\\s*)*)*|Directors*\\s*|Specialists*\\s*|Admin\\s*|Faculty\\s*|College\\s*|\\w+olo*g(y|ie|ia)\\s*|Admin(istration)*(\\s+Off(ice)*)*|Bioinformatics|Scott|Morris|Hilton|Prof(essional)*|IRD|Shapiro|MAin|Hoblitezele|Maloney|Gell|Dickson|Mayo|Legacy|Outpatient\\s*|Tower\\s*|\\w+\\s+Building\\s*|Call|Care|Bexley)\\s*$", " ", x, ignore.case = T)
# Street Fixes
## ALL
x <- gsub("(^|\\s+)Avenue(\\s+|\\s*$)", " Ave ", x, ignore.case = T)
# Annexes and Offices
x <- gsub("^(?=.*Annexe*)(?!.*(\\d+-\\d+-\\d+))(?!.*(\\s+(Rd|St|Dr)|Ro))(?!.*Ave(nue)*)(?!.*Rue|Via|Plaza|Blvd|Marg).*$", " ", x, ignore.case = T, perl = T)
x <- gsub("^(?=.*Off(ices*)*\\s+)(?!.*(Rd|St|Dr))(?!.*Ave(nue)*)(?!.*Rue|Via|Plaza|Blvd|Marg).*$", " ", x, ignore.case = T, perl = T)
x <- gsub("(^|\\s+|-)(Mec\\s*)*(Euclid\\s+)*(Medical\\s*)*(Directors\\s+)*(Clinical\\s*(Trials\\s*)*)*(Site Management\\s*)*(Aseptic\\s*)*(Can\\s*cer\\s*)*(Re\\s*s(earch)*\\s*)*(Services\\s*)*(Directors\\s*)*(Specialist\\s*)*(Admin\\s*)*(Faculty\\s*)*(College\\s*)*(\\w+olo*g(y|ie|ia)\\s*)*(Outpatient\\s*)*Offi*c*e*s*(\\s*-*|\\s+)(\\d+|\\D\\d*|\\d+\\w|\\d+-\\d+)*(Tower\\s*)*(\\s+|$)(?!\\s+Park)", " ", x, perl = T, ignore.case = T)
# Investigational
x <- gsub("(^|\\s+)(Estudios de\\s*)*(Group*\\s*)*Investiga(t|c)i*ona*l*\\s+Drug(\\s+|$)", " ", x, ignore.case = T)
x <- gsub("(^|\\s+)*Invest((i|a)ga(t|c)iona*l*)*\\s+(Drug|Chemo)(\\s+|$)", " ", x, ignore.case = T)
# Standard site names
x <- gsub("^(?=.*Hos*pital)(?!.*(^|\\s+)(Calle|Rd|St|Dr|Rue|Via|Plaza|Blvd|Marg|Av\\.|Ave)(\\s+|$)).*$", " ", x, ignore.case = T, perl = T)
x <- gsub("^(?=.*Cent(re|er))(?!.*(^|\\s+)(Rd|St|Dr|Av(\\.|e)|Rue|Via|Plaza|Blvd|Marg|Ct|Pl|P(ar)*kwa*y|Way|Paseo)(\\s+|$))(?!.*\\d+).*$", " ", x, perl = T, ignore.case = T)
x <- gsub("(^|\\s+)Research\\s+Cent(re|er)(\\s+|$)", " ", x, perl = T, ignore.case = T)
x <- gsub("^(?=.*Clini(c|que)s)(?!.*(^|\\s+)(Rd|Str|Dr|Av(\\.|e)|Rue|Allee|Via|Plaza|Blvd|Marg|Ct|Pl|P(ar)*kwa*y|Way|Paseo)(\\s+|$)).*$", " ", x, perl = T, ignore.case = T)
x <- gsub("^(?=.*KliniK)(?!.*(^|\\s+)(Rd|St|Str|Dr|Av(\\.|e)|Rue|Via|Plaza|Blvd|Marg|Ct|Pl|P(ar)*kwa*y|Way|Paseo)(\\s+|$))(?!.*strasse|strabe|park).*$", " ", x, perl = T, ignore.case = T)
### Eliminate Shrapnel
x <- gsub("^\\s*\\d+\\s*\\d*\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*pharmacy\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\d?\\s*\\w?\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*Level\\d+\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\w+(-\\w+)*\\d+\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\w{1,3}\\s*$", " ", x, ignore.case = T)
x <- gsub("^\\s*\\w{1,2}\\d+\\s*\\w{1,2}$", " ", x, ignore.case = T)
x <- gsub("^\\s*Wacc\\s*\\d+\\s*\\w{1,2}$", " ", x, ignore.case = T)
x <- gsub("\\s+", " ", x, ignore.case = T)
x <- trimws(x)
x <- gsub("^$", NA, x, ignore.case = T)
x <- gsub("^\\s+$", NA, x, ignore.case = T)
}

CntryCondStSwpR <- function(x, y) {
### Building Purges
## Country Specific
x <-  ifelse(!(y %in% c("Japan","Korea")), gsub("^(?=.*Universit(y|e|ario|aire))(?!.*\\s+(Rd|St|Dr))(?!.*Ave(nue)*)(?!.*\\s+Rue|Via|Plaza|Blvd|Marg).*$", " ", x, ignore.case = T, perl = T), x)
x <-  ifelse(!(y %in% c("Japan","Korea")), gsub("^(?=.*Building)(?!.*(Rd|St|Dr))(?!.*Ave(nue)*)(?!.*Rue|Via|Plaza|Blvd|Marg).*$", " ", x, ignore.case = T, perl = T), x)
x <-  ifelse(!(y %in% c("Japan","Korea")), gsub("(^|\\s+)(Admin\\s+)*(Bunting\\s+)*(Blaustein\\s+)*(Shapiro\\s+)*(Clinical\\s+)*(Cancer\\s+)*(Research\\s+)*(Science\\s+)*(Medical\\s+)*(Arts\\s+)*(School\\s+)*Building(\\s+|$)", " ", x, ignore.case = T, perl = T), x)
# Chome builder
x <-  ifelse(y %in% c("Japan"), gsub("(^|\\s+)([\\d+])-([\\d+])-([\\d+])(\\s+|$)", "\\1 ", x, ignore.case = T, perl = T), x)
## RUS
x <-  ifelse(y %in% c("Russia"), gsub("(^|\\s+)St(\\s+|$)", " Ul. ", x, ignore.case = T, perl = T), x)
## POL
x <-  ifelse(y %in% c("Poland"), gsub("^\\s*St\\s+", "", x, ignore.case = T, perl = T), x)
}

LangCondStSwpR <- function(x, y) {
### Lang Specific
## ESP
x <-  ifelse(y %in% c("es", "pt"), gsub("^\\s*Avenida\\s+", "Av. ", x, ignore.case = T, perl = T), x)
## ENG
x <-  ifelse(y %in% c("en"), gsub("(^|\\s+)Boule*vard(\\s+|$)", " Blvd ", x, ignore.case = T, perl = T), x)
}